/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int on_allcap_check(int, int);

int on_allcap_check(int owned_count __attribute__((unused)), int total_count __attribute__((unused))) {
    return ((total_count > 0) && (owned_count == total_count));
}

