/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

void on_moon_zenith(int, int);

void on_moon_zenith(int x __attribute__((unused)), int z __attribute__((unused))) {
    redgarden_host_spawn_bloodflower(x, z); reflux_dispatch(REFLUX_ACTION_BLOODFLOWER_TRIGGERED, x, z, 0);
}

