/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int on_bloodflower_hostile_spawner_should_react(int);
int on_bloodflower_hostile_spawner_creep_count();

int on_bloodflower_hostile_spawner_should_react(int action_type __attribute__((unused))) {
    return ((action_type == REFLUX_ACTION_BLOODFLOWER_TRIGGERED));
}

int on_bloodflower_hostile_spawner_creep_count(void) {
    return 5;
}

