/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

void on_hero_kill(int, int);
void on_item_purchase(int, int, int);
void on_node_capture(int, int);
void on_node_uncapture(int, int);
void on_king_spawn(int);

void on_hero_kill(int victim __attribute__((unused)), int killer __attribute__((unused))) {
    redgarden_host_log_kill(victim, killer);
}

void on_item_purchase(int buyer __attribute__((unused)), int item_id __attribute__((unused)), int cost __attribute__((unused))) {
    redgarden_host_log_purchase(buyer, item_id, cost);
}

void on_node_capture(int node_id __attribute__((unused)), int team __attribute__((unused))) {
    redgarden_host_log_node_capture(node_id, team);
}

void on_node_uncapture(int node_id __attribute__((unused)), int team __attribute__((unused))) {
    redgarden_host_log_node_uncapture(node_id, team);
}

void on_king_spawn(int camp_id __attribute__((unused))) {
    redgarden_host_log_king_spawn(camp_id);
}

