/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int on_frontier_village_spawn_interval_ms(int, int);
int on_frontier_village_should_raise_militia(int, int);
int on_frontier_village_convert_resistance(int, int);

int on_frontier_village_spawn_interval_ms(int population __attribute__((unused)), int militia __attribute__((unused))) {
    int total __attribute__((unused)) = (population + militia);
    int interval __attribute__((unused)) = (8000 - (total * 150));
    if ((interval < 2000)) {
    return 2000;
    } else {
    return interval;
    }
}

int on_frontier_village_should_raise_militia(int population __attribute__((unused)), int militia __attribute__((unused))) {
    return ((population >= 5) && ((population % 3) == 2));
}

int on_frontier_village_convert_resistance(int population __attribute__((unused)), int militia __attribute__((unused))) {
    return (20 + (militia * 4));
}

