/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

void on_town_captured(int, int, int);

void on_town_captured(int town_id __attribute__((unused)), int old_faction __attribute__((unused)), int new_faction __attribute__((unused))) {
    reflux_dispatch(REFLUX_ACTION_TOWN_CAPPED, town_id, old_faction, new_faction);
}

