/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int on_walled_hamlet_spawn_interval_ms(int, int);
int on_walled_hamlet_should_raise_militia(int, int);
int on_walled_hamlet_convert_resistance(int, int);
int on_walled_hamlet_defense_range(int);
int on_walled_hamlet_defense_damage(int);

int on_walled_hamlet_spawn_interval_ms(int population __attribute__((unused)), int militia __attribute__((unused))) {
    int total __attribute__((unused)) = (population + militia);
    int interval __attribute__((unused)) = (10000 - (total * 100));
    if ((interval < 4000)) {
    return 4000;
    } else {
    return interval;
    }
}

int on_walled_hamlet_should_raise_militia(int population __attribute__((unused)), int militia __attribute__((unused))) {
    return ((population >= 3) && ((population % 2) == 1));
}

int on_walled_hamlet_convert_resistance(int population __attribute__((unused)), int militia __attribute__((unused))) {
    return (60 + (militia * 8));
}

int on_walled_hamlet_defense_range(int militia __attribute__((unused))) {
    return (1 + (militia / 3));
}

int on_walled_hamlet_defense_damage(int militia __attribute__((unused))) {
    return (5 + (militia * 2));
}

